
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ing. Diego Romero
 * @version 1.0
 * @fecha 2015-05-01
 */
public class Login extends javax.swing.JFrame {

    Connection c;

    /**
     * Creates new form Login
     *
     * @param c
     */
    public Login(Connection c) {
        this.c = c;
        try {
            UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {

        }
        initComponents();
        setIconImage(new javax.swing.ImageIcon("src/cel logo.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso al sistema");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(38, 169, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtUser.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 0, 204));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setToolTipText("Ingrese su usuario");
        txtUser.setCaretColor(new java.awt.Color(255, 0, 0));
        txtUser.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtUser.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 50);
        jPanel1.add(txtUser, gridBagConstraints);

        jLabel2.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Clave");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        txtClave.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 204));
        txtClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClave.setToolTipText("Ingrese su clave");
        txtClave.setCaretColor(new java.awt.Color(255, 0, 0));
        txtClave.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtClave.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClaveKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(txtClave, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(299, 294));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar())
                && !Character.isDigit(evt.getKeyChar())
                && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyTyped

    }//GEN-LAST:event_txtClaveKeyTyped

    private void txtClaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyReleased
        //Cuando presiona Enter y los campo no estan vacios valida
        if (evt.getKeyCode() == 10 && !txtClave.getText().isEmpty() && !txtUser.getText().isEmpty()) {

            Funciones f = new Funciones();
            if (f.login(c, txtUser.getText(), txtClave.getText())) {
                dispose();
                new RegistroDocente(ConexionBD.getConecion()).setVisible(true);
            } else {
                txtUser.setText("");
                txtClave.setText("");
                JOptionPane.showMessageDialog(rootPane, "Usuario o clave incorrectos");
            }
        }
    }//GEN-LAST:event_txtClaveKeyReleased
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
