
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ing. Diego Romero
 * @version 1.0
 * @fecha 2015-05-01
 */
public class RegistroDocente extends javax.swing.JFrame {

    Connection c;

    /**
     * Creates new form Login
     *
     * @param c
     */
    public RegistroDocente(Connection c) {
        this.c = c;
        try {
            UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {

        }
        initComponents();
        setIconImage(new javax.swing.ImageIcon("src/cel logo.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtApe = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtFec = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de docentes");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(38, 169, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtNombres.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(0, 0, 204));
        txtNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombres.setToolTipText("Ingrese dos nombres");
        txtNombres.setCaretColor(new java.awt.Color(255, 0, 0));
        txtNombres.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtNombres.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 22);
        jPanel1.add(txtNombres, gridBagConstraints);

        jLabel2.setText("DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Nombres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Celular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Fecha de nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Cargo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        txtApe.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtApe.setForeground(new java.awt.Color(0, 0, 204));
        txtApe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApe.setToolTipText("Ingrese dos apellidos");
        txtApe.setCaretColor(new java.awt.Color(255, 0, 0));
        txtApe.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtApe.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 22);
        jPanel1.add(txtApe, gridBagConstraints);

        txtCargo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtCargo.setForeground(new java.awt.Color(0, 0, 204));
        txtCargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCargo.setToolTipText("Ingrese su usuario");
        txtCargo.setCaretColor(new java.awt.Color(255, 0, 0));
        txtCargo.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtCargo.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCargoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCargoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 225;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 22);
        jPanel1.add(txtCargo, gridBagConstraints);

        txtCel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtCel.setForeground(new java.awt.Color(0, 0, 204));
        txtCel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCel.setToolTipText("Ingrese su usuario");
        txtCel.setCaretColor(new java.awt.Color(255, 0, 0));
        txtCel.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtCel.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 22);
        jPanel1.add(txtCel, gridBagConstraints);

        txtCor.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtCor.setForeground(new java.awt.Color(0, 0, 204));
        txtCor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCor.setToolTipText("Ingrese su usuario");
        txtCor.setCaretColor(new java.awt.Color(255, 0, 0));
        txtCor.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtCor.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 280;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 22);
        jPanel1.add(txtCor, gridBagConstraints);

        txtFec.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtFec.setForeground(new java.awt.Color(0, 0, 204));
        txtFec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFec.setText("1950-01-01");
        txtFec.setToolTipText("Ingrese fecha de nacimiento");
        txtFec.setCaretColor(new java.awt.Color(255, 0, 0));
        txtFec.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtFec.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtFec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFecKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 22);
        jPanel1.add(txtFec, gridBagConstraints);

        txtDni.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtDni.setForeground(new java.awt.Color(0, 0, 204));
        txtDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDni.setToolTipText("Ingrese su usuario");
        txtDni.setCaretColor(new java.awt.Color(255, 0, 0));
        txtDni.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtDni.setSelectionColor(new java.awt.Color(51, 255, 51));
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 22);
        jPanel1.add(txtDni, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        jPanel1.add(jButton1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(605, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar())
                && evt.getKeyChar() != ' '
                && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar())
                && evt.getKeyChar() != ' '
                && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApeKeyTyped

    private void txtCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar())
                && evt.getKeyChar() != ' '
                && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCargoKeyTyped

    private void txtCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelKeyTyped
        if (txtCel.getText().length()>9||(!Character.isDigit(evt.getKeyChar())
                && !Character.isISOControl(evt.getKeyChar()))) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCelKeyTyped

    private void txtCorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar())
                && !Character.isDigit(evt.getKeyChar())
                && evt.getKeyChar() != '.'
                && evt.getKeyChar() != '_'
                && evt.getKeyChar() != '@'
                && evt.getKeyChar() != '-'
                && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCorKeyTyped

    private void txtFecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFecKeyTyped
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyChar() != '-'
                && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtFecKeyTyped

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        if (!Character.isDigit(evt.getKeyChar())
                && !Character.isAlphabetic(evt.getKeyChar())
                && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDniKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Funciones f = new Funciones();
        if (f.registrarDocente(c, txtCargo.getText(), txtDni.getText(), txtNombres.getText(),
                txtApe.getText(), txtCel.getText(), txtCor.getText(), txtFec.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Docente Registrado correctamente");
            dispose();
            new RegistroDocente(ConexionBD.getConecion()).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se pudo registrar");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        txtNombres.setText(txtNombres.getText().toUpperCase());
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtApeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeKeyReleased
        txtApe.setText(txtApe.getText().toUpperCase());
    }//GEN-LAST:event_txtApeKeyReleased

    private void txtCargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyReleased
        txtCargo.setText(txtCargo.getText().toUpperCase());
    }//GEN-LAST:event_txtCargoKeyReleased

    private void txtCorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorKeyReleased
        txtCor.setText(txtCor.getText().toLowerCase());
    }//GEN-LAST:event_txtCorKeyReleased
    public static void main(String[] args) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFec;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
